[project]
name = "mcp-client"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Raza", email = "official.razarehman@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "langchain>=1.3.15",
    "langchain-mcp-adapters>=0.3.2",
    "langchain-openai>=1.5.0",
    "python-dotenv>=1.2.2",
    "streamlit>=1.61.1",
]

[project.scripts]
mcp-client = "mcp_client:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
